apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  #namespace: basic-web-deployment-with-nginx
  labels:
    name: redis-pod
  annotations:
    name: redis-pod
spec:
  containers:
    - name: rediscontainer
      image: redis
      imagePullPolicy: IfNotPresent # Always|Nerver|IfNotPresent
      # command: string
      # workingDir: string
      # volumeMounts:
      #   - name: string
      #     mountPath: string
      #     readOnly: boolean
      ports:
        - name: redisport
          containerPort: 6379
      #     hostPort: Int
      #     protocol: string # TCP|UDP
      # livenessProbe:
      #   httpGet:
      #     path: /healthz
      #     port: 8080
      #   initialDelaySeconds: 3
      #   periodSeconds: 3
      # env:
      #   - name: string
      #     value: string
      # resources:
      #     requests:
      #       limits:
      #         cpu: string
      #         memory: string
      # volumes:
      #   - name: string
      #     emptyDir: {}
      #     hostPath:
      #       path: string
  dnsPolicy: Default # Default|ClusterFirst
  restartPolicy: Always # Always|OnFailure
  # nodeSeletor:
  #   name: string
  # imagePullSecrets:
  #   name: string