apiVersion: v1
kind: Pod
metadata:
  name: web-pod-config
  namespace: basic-web-deployment-with-nginx
  labels:
    name: web-pod
  annotations:
    name: web-pod
spec:
  containers:
    - name: web-container
      image: flask-image:latest
      imagePullPolicy: Never # Always|Nerver|IfNotPresent
      # command: string
      # workingDir: string
      # volumeMounts:
      #   - name: string
      #     mountPath: string
      #     readOnly: boolean
      ports:
        - name: containerport
          containerPort: 9000
      #     hostPort: Int
      #     protocol: string # TCP|UDP
      # livenessProbe:
      #   httpGet:
      #     path: /healthz
      #     port: 8080
      #   initialDelaySeconds: 3
      #   periodSeconds: 3
      #env:
      #   - name: string
      #     value: string
      # resources:
      #     requests:
      #       limits:
      #         cpu: string
      #         memory: string
      # volumes:
      #   - name: string
      #     emptyDir: {}
      #     hostPath:
      #       path: string
  dnsPolicy: Default # Default|ClusterFirst
  restartPolicy: Always # Always|OnFailure
  # nodeSeletor:
  #   name: string
  # imagePullSecrets:
  #   name: string